on:
  workflow_call:
    inputs:
      golang-version:
        default: "1.21"
        description: |
          Set the version for golang
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/community-plugin-ci.yml
    secrets: inherit
    with:
      golang-version: ${{ inputs.golang-version }}

  release-github:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: cd/checkout-repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: "0"

      - name: cd/download-artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: dist
          path: dist

      - name: ci/publish-release
        working-directory: dist
        run: |
          gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" --notes-file release-notes.md  *.tar.gz
