on:
  workflow_call:
    inputs:
      golangci-lint-version:
        default: "v1.55.2"
        description: |
          Set the version for golangci-lint
        required: false
        type: string

      golang-version:
        default: "1.21"
        description: |
          Set the version for golang
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@main
        with:
          golangci-lint-version: ${{ inputs.golangci-lint-version }}
          golang-version: ${{ inputs.golang-version }}

      - name: ci/lint
        uses: mattermost/actions/plugin-ci/lint@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@main
        with:
          golangci-lint-version: ${{ inputs.golangci-lint-version }}
          golang-version: ${{ inputs.golang-version }}

      - name: ci/test
        uses: mattermost/actions/plugin-ci/test@main

  build:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@main
        with:
          golang-version: ${{ inputs.golang-version }}
          golangci-lint-version: ${{ inputs.golangci-lint-version }}

      - name: ci/build
        uses: mattermost/actions/plugin-ci/build@main
