on:
  workflow_call:
    inputs:
      artifacts:
        default: dist
        description: |
          The path or files of artifacts to upload
        required: false
        type: string

      bucket:
        default: mattermost-plugins-ci/ci/
        description: |
          The S3 bucket full path to upload
        required: false
        type: string

      golang-cache-enabled:
        default: true
        description: |
          Enable golang caching in CI
        required: false
        type: boolean

      golang-version:
        default: "1.19"
        description: |
          Set the version for Golang
        required: false
        type: string

      golangci-lint-version:
        default: "v1.49.0"
        description: |
          Set the version for golangci-lint
        required: false
        type: string

      region:
        default: us-east-2
        description: |
          The AWS region for S3 bucket
        required: false
        type: string

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ inputs.golang-version }}
          cache: true

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@a137067c750390bfc228375dbe745b2aa3a566e8

      - name: ci/lint
        uses: mattermost/actions/plugin-ci/lint@a137067c750390bfc228375dbe745b2aa3a566e8

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ inputs.golang-version }}
          cache: true

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@a137067c750390bfc228375dbe745b2aa3a566e8

      - name: ci/test
        uses: mattermost/actions/plugin-ci/test@a137067c750390bfc228375dbe745b2aa3a566e8

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ inputs.golang-version }}
          cache: true

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@a137067c750390bfc228375dbe745b2aa3a566e8

      - name: ci/build
        uses: mattermost/actions/plugin-ci/build@a137067c750390bfc228375dbe745b2aa3a566e8

  delivery:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: ci/download-artifact
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # v3.0.1
        with:
          name: dist
          path: dist

      - name: ci/prepare-artifact
        run: mv dist/*.tar.gz dist/$GITHUB_REPOSITORY-ci.tar.gz

      - name: ci/aws-configure
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ secrets.PLUGIN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PLUGIN_AWS_SECRET_ACCESS_KEY }}

      - name: ci/artifact-upload
        shell: bash
        run: |
          aws s3 cp ${{ inputs.artifacts }} s3://${{ inputs.bucket }} --acl public-read --cache-control no-cache
